# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='action_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
