# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0002_worklog_action_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='action_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
