# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0003_auto_20170625_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBeacon',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('major', models.CharField(blank=True, max_length=5)),
                ('minor', models.CharField(blank=True, max_length=5)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
