# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0004_localbeacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
